name: Build Firmware Container
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: Install Native Legacy Dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip file python
      - name: Build Firmware
        run: |
          wget https://archive.openwrt.org/releases/18.06.9/targets/ar71xx/tiny/openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64.tar.xz
          cd openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64
          make image PROFILE=tl-wa850re-v1 PACKAGES="-wpad-mini -wpad-basic wpad-wolfssl -luci -ppp -ppp-mod-pppoe -kmod-ppp -kmod-pppoe -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables"
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eduroam-firmware-guaranteed
          path: openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64/bin/targets/ar71xx/tiny/*sysupgrade.bin
