name: Build Firmware Direct
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip file gcc g++ python2 python3
          sudo ln -sf /usr/bin/python2 /usr/bin/python
      - name: Build Firmware
        run: |
          wget https://archive.openwrt.org/releases/18.06.9/targets/ar71xx/tiny/openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64.tar.xz
          cd openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64
          make image PROFILE=tl-wa850re-v1 PACKAGES="-wpad-mini -wpad-basic wpad-wolfssl -luci -ppp -ppp-mod-pppoe -kmod-ppp -kmod-pppoe -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables"
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eduroam-firmware-final
          path: openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64/bin/targets/ar71xx/tiny/*sysupgrade.bin
